services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=8080
    restart: unless-stopped

networks:
  default:
    driver: bridge
